# Generated by Django 6.0 on 2026-02-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employee_role_employee_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interaction',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.RenameField(
            model_name='interaction',
            old_name='next_follow_up',
            new_name='follow_up_date',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='client',
        ),
        migrations.AddField(
            model_name='interaction',
            name='client_contact',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='interaction',
            name='client_name',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='interaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='follow_up_time',
            field=models.TimeField(default='10:00:00'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='interaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='discussion_notes',
            field=models.TextField(blank=True),
        ),
    ]
