# Generated by Django 6.0 on 2026-02-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_interaction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='sale',
            name='client',
        ),
        migrations.AddField(
            model_name='sale',
            name='client_name',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='frequency',
            field=models.CharField(choices=[('M', 'Monthly'), ('Q', 'Quarterly'), ('H', 'Half Yearly'), ('Y', 'Yearly'), ('O', 'One Time')], max_length=1),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.CharField(choices=[('MF', 'Mutual Funds'), ('HI', 'Health Insurance'), ('GI', 'General Insurance'), ('LI', 'Life Insurance'), ('NCD', 'NCDs'), ('MLD', 'MLDs'), ('BOND', 'Bonds'), ('CFD', 'Corporate FDs'), ('AIF', 'AIFs'), ('PMS', 'PMS'), ('ADV', 'Advisory'), ('SB', 'Shares Broking'), ('US', 'Unlisted Shares'), ('RE', 'Real Estate'), ('LOAN', 'Loans'), ('WILL', 'Will Making')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='scheme',
            field=models.CharField(max_length=200),
        ),
    ]
