# version: "3.9"

services:
  web:
    build: .
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --workers 1 --timeout 120 --log-level debug
    ports:
      - "8000:8000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A backend worker -l info
    depends_on:
      - redis
    volumes:
      - .:/app